//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadCabelereiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Atendimento = new HashSet<Atendimento>();
        }
    
        public int pk_id_cliente { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
    
        public virtual ICollection<Atendimento> Atendimento { get; set; }
    }
}
