//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadCabelereiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_atendimento
    {
        public int pk_id_item_atendimento { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<int> fk_id_atendimento { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> fk_id_servico { get; set; }
    
        public virtual Atendimento Atendimento { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
