//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadCabelereiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public Servico()
        {
            this.Item_atendimento = new HashSet<Item_atendimento>();
        }
    
        public int pk_id_servico { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<double> tempo_medio_execucao { get; set; }
    
        public virtual ICollection<Item_atendimento> Item_atendimento { get; set; }
    }
}
